export const STUDY_TOPIC_COPY = Object.freeze({
  screenTitle: "수학 학습",
  screenSubtitle: "학년과 주제를 골라 원하는 만큼 풀어 봐요.",
  back: "뒤로",
  backHome: "돌아가기",
  learnerLoading: "학습 정보를 불러오고 있어요.",
  learnerLoadError: "학습 정보를 불러오지 못했어요.",
  missionLoading: "문제를 불러오고 있어요.",
  chooseGradeTitle: "몇 학년 수학을 풀어볼까?",
  chooseGradeHelp: "학년을 누르면 배울 수 있는 세부 개념을 보여 줄게요.",
  gradeLabel: (grade: number) => `${grade}학년`,
  gradeLoading: "주제 불러오는 중",
  gradeRetry: "주제를 불러오지 못했어요. 다시 눌러 주세요.",
  chooseTopicTitle: "어떤 주제를 풀어볼까?",
  chooseTopicHelp: "골고루 풀거나 원하는 세부 개념만 계속 연습할 수 있어요.",
  adaptiveTitle: "골고루 풀기",
  adaptiveDescription: "지금 필요한 여러 개념을 섞어서 풀어요.",
  conceptProblemCount: (count: number) => `${count}가지 문제`,
  changeGrade: "학년 다시 고르기",
  changeTopic: "주제 바꾸기",
  continuous: "계속 학습 중",
  nextLoading: "다음 문제를 준비하고 있어요.",
  topicLoading: "세부 개념을 불러오고 있어요.",
  startError: "학습을 시작하지 못했어요. 다시 눌러 주세요.",
  abandonError: "주제를 바꾸지 못했어요. 잠시 후 다시 눌러 주세요.",
  retry: "다시 시도",
} as const);
