export const STUDY_TOPIC_COPY = Object.freeze({
  screenTitle: "수학 학습",
  screenSubtitle: "학년과 주제를 골라 원하는 만큼 풀어 봐.",
  back: "뒤로",
  backHome: "돌아가기",
  learnerLoading: "학습 정보를 불러오고 있어.",
  learnerLoadError: "학습 정보를 불러오지 못했어.",
  missionLoading: "문제를 불러오고 있어.",
  resumeTitle: "하던 학습이 있어",
  resumeDescription: "이어 풀거나 다른 학년과 주제를 골라 새로 시작할 수 있어.",
  resumeAction: "학습 이어하기",
  differentAction: "다른 내용 학습하기",
  chooseGradeTitle: "몇 학년 수학을 풀어볼까?",
  chooseGradeHelp: "학년을 누르면 배울 수 있는 세부 개념을 보여 줄게.",
  gradeLabel: (grade: number) => `${grade}학년`,
  gradeLoading: "주제 불러오는 중",
  gradeRetry: "주제를 불러오지 못했어. 다시 눌러 줘.",
  chooseTopicTitle: "어떤 주제를 풀어볼까?",
  chooseTopicHelp: "골고루 풀거나 원하는 세부 개념만 계속 연습할 수 있어.",
  adaptiveTitle: "골고루 풀기",
  adaptiveDescription: "지금 필요한 여러 개념을 섞어서 풀어 봐.",
  conceptProblemCount: (count: number) => `${count}가지 문제`,
  changeGrade: "학년 다시 고르기",
  changeTopic: "다른 내용 풀기",
  continuous: "계속 학습 중",
  nextLoading: "다음 문제를 준비하고 있어.",
  topicLoading: "세부 개념을 불러오고 있어.",
  startError: "학습을 시작하지 못했어. 다시 눌러 줘.",
  abandonError: "주제를 바꾸지 못했어. 잠시 후 다시 눌러 줘.",
  retry: "다시 시도",
} as const);
