/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=worker/wrangler.toml --include-runtime=false worker/worker-configuration.d.ts` (hash: 3e147fb6e2ba8f968d0d06d9a3394e8a)
interface __BaseEnv_Env {
	PHOTOS: R2Bucket;
	DB: D1Database;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	OPENAI_BASE_URL: "https://gateway.ai.cloudflare.com/v1/e0e6ad13899508a76975d40b23d0bd26/hyeni-ai/openai";
	FAMILY_ROOM: DurableObjectNamespace<import("./index").FamilyRoom>;
	TEACHER_ROOM: DurableObjectNamespace<import("./index").TeacherRoom>;
	STUDY_SERVICE: Service /* entrypoint CalendarStudyService from hyeni-study */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "FamilyRoom" | "TeacherRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENAI_BASE_URL">> {}
}
