-- 플로팅 AI 친구가 스스로 아이를 부르는 동작의 부모 스위치. 2026-08-19.
--
-- 아이 화면 구석의 작은 버튼은 그냥 지나치므로, 친구가 가끔 커졌다가 화면을 채우고
-- 다시 작아지며 말을 건다. 이건 아이 화면을 잠깐 가리는 동작이라 부모가 끌 수 있어야 한다.
--
-- 기본값은 1(켜짐)이다 — 아이가 AI 친구를 발견하게 하는 것이 이 기능의 목적이고,
-- 부담스러운 가족은 부모 설정 > AI 친구에서 끄면 된다. 끄면 부르지 않지만
-- 부모님 메시지·다음 일정·준비물을 말풍선으로 알려 주는 기본 동작은 그대로 유지된다.
--
-- SQLite(D1)는 ADD COLUMN IF NOT EXISTS를 지원하지 않으므로 운영에서 1회만 실행한다.
-- 이미 적용된 DB에서 다시 실행하면 duplicate column name 으로 실패하고 롤백된다(무해).
ALTER TABLE ai_parent_settings ADD COLUMN buddy_attention_enabled INTEGER DEFAULT 1 NOT NULL;
